// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uompjtduifsbykkfryor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvbXBqdGR1aWZzYnlra2ZyeW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDExNzksImV4cCI6MjA2OTcxNzE3OX0.AWbnssup8jMguOMK4cFbRP7SbVwU3ycKrskN4DIuabE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});